// Mock data for dishes
export interface Dish {
  id: string
  name: string
  description: string
  image: string
  carbonScore: "Low" | "Medium" | "High"
  carbonFootprint: number // in kg CO2e
  nutrition: {
    calories: number
    protein: number // in grams
    fiber: number // in grams
    fat: number // in grams
    carbs: number // in grams
  }
  ethnoTag: string[]
  price: number
  currency: string // Added currency field
  popularity: number // 1-10 scale
  ingredients: string[]
  allergens: string[]
  isVegetarian: boolean
  isVegan: boolean
  isGlutenFree: boolean
}

export const dishes: Dish[] = [
  {
    id: "1",
    name: "Mediterranean Chickpea Bowl",
    description: "A protein-rich bowl with chickpeas, quinoa, cucumber, tomatoes, and tahini dressing",
    image: "/images/dishes/mediterranean-chickpea-bowl.jpg",
    carbonScore: "Low",
    carbonFootprint: 0.7,
    nutrition: {
      calories: 450,
      protein: 15,
      fiber: 12,
      fat: 18,
      carbs: 65,
    },
    ethnoTag: ["Mediterranean", "Middle Eastern"],
    price: 220,
    currency: "₹",
    popularity: 8,
    ingredients: ["Chickpeas", "Quinoa", "Cucumber", "Tomatoes", "Tahini", "Olive Oil", "Lemon Juice", "Parsley"],
    allergens: ["Sesame"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: "2",
    name: "Tofu Pad Thai",
    description: "Classic Thai noodle dish with tofu, bean sprouts, and peanuts",
    image: "/images/dishes/tofu-pad-thai.jpg",
    carbonScore: "Medium",
    carbonFootprint: 1.2,
    nutrition: {
      calories: 520,
      protein: 18,
      fiber: 6,
      fat: 22,
      carbs: 70,
    },
    ethnoTag: ["Thai", "Asian"],
    price: 250,
    currency: "₹",
    popularity: 9,
    ingredients: ["Rice Noodles", "Tofu", "Bean Sprouts", "Peanuts", "Lime", "Tamarind", "Green Onions"],
    allergens: ["Peanuts", "Soy"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: "3",
    name: "Black Bean Burrito",
    description: "Hearty burrito with black beans, rice, salsa, and guacamole",
    image: "/images/dishes/black-bean-burrito.jpg",
    carbonScore: "Low",
    carbonFootprint: 0.9,
    nutrition: {
      calories: 580,
      protein: 20,
      fiber: 15,
      fat: 25,
      carbs: 75,
    },
    ethnoTag: ["Mexican", "Latin American"],
    price: 200,
    currency: "₹",
    popularity: 9,
    ingredients: ["Whole Wheat Tortilla", "Black Beans", "Brown Rice", "Salsa", "Avocado", "Cilantro", "Lime"],
    allergens: ["Wheat"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
  },
  {
    id: "4",
    name: "Lentil Daal with Rice",
    description: "Spiced lentil stew served with basmati rice and naan",
    image: "/images/dishes/lentil-daal.jpg",
    carbonScore: "Low",
    carbonFootprint: 0.8,
    nutrition: {
      calories: 490,
      protein: 18,
      fiber: 14,
      fat: 12,
      carbs: 80,
    },
    ethnoTag: ["Indian", "South Asian"],
    price: 180,
    currency: "₹",
    popularity: 7,
    ingredients: ["Red Lentils", "Basmati Rice", "Tomatoes", "Onions", "Garlic", "Ginger", "Cumin", "Turmeric"],
    allergens: ["None"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: "5",
    name: "Grilled Chicken Caesar Salad",
    description: "Classic Caesar salad with grilled chicken breast and homemade dressing",
    image: "/images/dishes/chicken-caesar-salad.jpg",
    carbonScore: "Medium",
    carbonFootprint: 2.1,
    nutrition: {
      calories: 420,
      protein: 35,
      fiber: 5,
      fat: 22,
      carbs: 20,
    },
    ethnoTag: ["Italian", "American"],
    price: 280,
    currency: "₹",
    popularity: 8,
    ingredients: ["Chicken Breast", "Romaine Lettuce", "Parmesan Cheese", "Croutons", "Caesar Dressing"],
    allergens: ["Dairy", "Wheat", "Eggs"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    id: "6",
    name: "Beef Burger with Fries",
    description: "Classic beef burger with lettuce, tomato, and a side of fries",
    image: "/images/dishes/beef-burger.jpg",
    carbonScore: "High",
    carbonFootprint: 5.8,
    nutrition: {
      calories: 850,
      protein: 40,
      fiber: 4,
      fat: 45,
      carbs: 80,
    },
    ethnoTag: ["American"],
    price: 300,
    currency: "₹",
    popularity: 10,
    ingredients: ["Beef Patty", "Burger Bun", "Lettuce", "Tomato", "Onion", "Cheese", "Potatoes"],
    allergens: ["Dairy", "Wheat"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    id: "7",
    name: "Vegetable Sushi Roll",
    description: "Fresh vegetable sushi rolls with avocado, cucumber, and carrot",
    image: "/images/dishes/vegetable-sushi.jpg",
    carbonScore: "Low",
    carbonFootprint: 0.6,
    nutrition: {
      calories: 320,
      protein: 8,
      fiber: 6,
      fat: 10,
      carbs: 55,
    },
    ethnoTag: ["Japanese", "Asian"],
    price: 240,
    currency: "₹",
    popularity: 7,
    ingredients: ["Sushi Rice", "Nori", "Avocado", "Cucumber", "Carrot", "Sesame Seeds"],
    allergens: ["Sesame"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: "8",
    name: "Falafel Wrap",
    description: "Crispy falafel with hummus, vegetables, and tahini in a wrap",
    image: "/images/dishes/falafel-wrap.jpg",
    carbonScore: "Low",
    carbonFootprint: 0.8,
    nutrition: {
      calories: 480,
      protein: 16,
      fiber: 12,
      fat: 22,
      carbs: 60,
    },
    ethnoTag: ["Middle Eastern", "Mediterranean"],
    price: 220,
    currency: "₹",
    popularity: 8,
    ingredients: ["Chickpeas", "Herbs", "Spices", "Whole Wheat Wrap", "Hummus", "Lettuce", "Tomato", "Tahini"],
    allergens: ["Wheat", "Sesame"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
  },
  {
    id: "9",
    name: "Mushroom Risotto",
    description: "Creamy Italian risotto with assorted mushrooms and parmesan",
    image: "/images/dishes/mushroom-risotto.jpg",
    carbonScore: "Medium",
    carbonFootprint: 1.5,
    nutrition: {
      calories: 550,
      protein: 12,
      fiber: 4,
      fat: 18,
      carbs: 85,
    },
    ethnoTag: ["Italian", "European"],
    price: 290,
    currency: "₹",
    popularity: 7,
    ingredients: ["Arborio Rice", "Mushrooms", "Onion", "Garlic", "White Wine", "Vegetable Broth", "Parmesan"],
    allergens: ["Dairy"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    id: "10",
    name: "Jollof Rice with Plantains",
    description: "Spiced West African rice dish served with fried sweet plantains",
    image: "/images/dishes/jollof-rice.jpg",
    carbonScore: "Medium",
    carbonFootprint: 1.3,
    nutrition: {
      calories: 520,
      protein: 10,
      fiber: 8,
      fat: 15,
      carbs: 90,
    },
    ethnoTag: ["West African", "Nigerian"],
    price: 250,
    currency: "₹",
    popularity: 8,
    ingredients: ["Rice", "Tomatoes", "Peppers", "Onions", "Spices", "Plantains"],
    allergens: ["None"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: "11",
    name: "Salmon Poke Bowl",
    description: "Fresh salmon poke bowl with rice, avocado, and seaweed",
    image: "/images/dishes/salmon-poke-bowl.jpg",
    carbonScore: "Medium",
    carbonFootprint: 2.3,
    nutrition: {
      calories: 480,
      protein: 30,
      fiber: 6,
      fat: 20,
      carbs: 50,
    },
    ethnoTag: ["Hawaiian", "Japanese"],
    price: 320,
    currency: "₹",
    popularity: 9,
    ingredients: ["Salmon", "Rice", "Avocado", "Cucumber", "Seaweed", "Soy Sauce", "Sesame Oil"],
    allergens: ["Fish", "Soy", "Sesame"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    id: "12",
    name: "Vegetable Biryani",
    description: "Fragrant Indian rice dish with mixed vegetables and aromatic spices",
    image: "/images/dishes/vegetable-biryani.jpg",
    carbonScore: "Low",
    carbonFootprint: 0.9,
    nutrition: {
      calories: 510,
      protein: 12,
      fiber: 10,
      fat: 16,
      carbs: 85,
    },
    ethnoTag: ["Indian", "South Asian"],
    price: 220,
    currency: "₹",
    popularity: 8,
    ingredients: ["Basmati Rice", "Mixed Vegetables", "Onions", "Garlic", "Ginger", "Spices", "Herbs"],
    allergens: ["None"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  // Adding more Indian dishes
  {
    id: "13",
    name: "Butter Chicken",
    description: "Tender chicken in a rich, creamy tomato sauce with butter and spices",
    image: "/images/dishes/butter-chicken.jpg",
    carbonScore: "Medium",
    carbonFootprint: 2.2,
    nutrition: {
      calories: 590,
      protein: 35,
      fiber: 3,
      fat: 42,
      carbs: 18,
    },
    ethnoTag: ["Indian", "North Indian"],
    price: 250,
    currency: "₹",
    popularity: 9,
    ingredients: ["Chicken", "Tomatoes", "Butter", "Cream", "Garam Masala", "Fenugreek", "Ginger", "Garlic"],
    allergens: ["Dairy"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    id: "14",
    name: "Palak Paneer",
    description: "Cottage cheese cubes in a creamy spinach gravy with Indian spices",
    image: "/images/dishes/palak-paneer.jpg",
    carbonScore: "Low",
    carbonFootprint: 0.8,
    nutrition: {
      calories: 340,
      protein: 18,
      fiber: 6,
      fat: 22,
      carbs: 16,
    },
    ethnoTag: ["Indian", "North Indian"],
    price: 180,
    currency: "₹",
    popularity: 8,
    ingredients: ["Paneer", "Spinach", "Onions", "Tomatoes", "Ginger", "Garlic", "Garam Masala", "Cream"],
    allergens: ["Dairy"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    id: "15",
    name: "Masala Dosa",
    description: "Crispy rice and lentil crepe filled with spiced potato filling, served with sambar and chutney",
    image: "/images/dishes/masala-dosa-new.jpg",
    carbonScore: "Low",
    carbonFootprint: 0.7,
    nutrition: {
      calories: 380,
      protein: 10,
      fiber: 8,
      fat: 12,
      carbs: 65,
    },
    ethnoTag: ["Indian", "South Indian"],
    price: 150,
    currency: "₹",
    popularity: 9,
    ingredients: ["Rice", "Lentils", "Potatoes", "Onions", "Mustard Seeds", "Curry Leaves", "Coconut Chutney"],
    allergens: ["None"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: "16",
    name: "Chole Bhature",
    description: "Spicy chickpea curry served with deep-fried bread",
    image: "/images/dishes/chole-bhature-new.jpg",
    carbonScore: "Medium",
    carbonFootprint: 1.4,
    nutrition: {
      calories: 650,
      protein: 20,
      fiber: 15,
      fat: 30,
      carbs: 75,
    },
    ethnoTag: ["Indian", "North Indian"],
    price: 160,
    currency: "₹",
    popularity: 8,
    ingredients: ["Chickpeas", "Onions", "Tomatoes", "Spices", "Flour", "Oil"],
    allergens: ["Wheat"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
  },
  {
    id: "17",
    name: "Idli Sambar",
    description: "Steamed rice cakes served with lentil vegetable stew and coconut chutney",
    image: "/images/dishes/idli-sambar-2.jpg",
    carbonScore: "Low",
    carbonFootprint: 0.6,
    nutrition: {
      calories: 280,
      protein: 10,
      fiber: 8,
      fat: 5,
      carbs: 50,
    },
    ethnoTag: ["Indian", "South Indian"],
    price: 120,
    currency: "₹",
    popularity: 7,
    ingredients: ["Rice", "Lentils", "Vegetables", "Tamarind", "Spices", "Coconut"],
    allergens: ["None"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: "18",
    name: "Rajma Chawal",
    description: "Kidney bean curry served with steamed rice, a North Indian comfort food",
    image: "/images/dishes/rajma-chawal.jpg",
    carbonScore: "Low",
    carbonFootprint: 0.8,
    nutrition: {
      calories: 440,
      protein: 16,
      fiber: 14,
      fat: 8,
      carbs: 80,
    },
    ethnoTag: ["Indian", "North Indian"],
    price: 140,
    currency: "₹",
    popularity: 8,
    ingredients: ["Kidney Beans", "Rice", "Onions", "Tomatoes", "Ginger", "Garlic", "Spices"],
    allergens: ["None"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
]

// Mock data for waste tracking
export interface WasteEntry {
  id: string
  date: string
  source: "Cafeteria" | "Event" | "Residential"
  foodType: string
  quantity: number // in kg
  disposalMethod: "Compost" | "Landfill" | "Donation"
  mealPeriod: "Breakfast" | "Lunch" | "Dinner" | "Special Event"
  notes: string
}

export const wasteEntries: WasteEntry[] = [
  {
    id: "1",
    date: "2024-04-15",
    source: "Cafeteria",
    foodType: "Vegetables",
    quantity: 5.2,
    disposalMethod: "Compost",
    mealPeriod: "Lunch",
    notes: "Mostly salad bar leftovers",
  },
  {
    id: "2",
    date: "2024-04-15",
    source: "Cafeteria",
    foodType: "Bread",
    quantity: 3.1,
    disposalMethod: "Donation",
    mealPeriod: "Dinner",
    notes: "Donated to local shelter",
  },
  {
    id: "3",
    date: "2024-04-16",
    source: "Event",
    foodType: "Mixed Food",
    quantity: 8.7,
    disposalMethod: "Compost",
    mealPeriod: "Special Event",
    notes: "Campus festival leftovers",
  },
  {
    id: "4",
    date: "2024-04-16",
    source: "Residential",
    foodType: "Dairy",
    quantity: 1.5,
    disposalMethod: "Landfill",
    mealPeriod: "Breakfast",
    notes: "Expired milk and yogurt",
  },
  {
    id: "5",
    date: "2024-04-17",
    source: "Cafeteria",
    foodType: "Meat",
    quantity: 2.8,
    disposalMethod: "Landfill",
    mealPeriod: "Dinner",
    notes: "Beef and chicken leftovers",
  },
  {
    id: "6",
    date: "2024-04-17",
    source: "Residential",
    foodType: "Fruits",
    quantity: 3.2,
    disposalMethod: "Compost",
    mealPeriod: "Breakfast",
    notes: "Overripe bananas and apples",
  },
  {
    id: "7",
    date: "2024-04-18",
    source: "Event",
    foodType: "Desserts",
    quantity: 4.5,
    disposalMethod: "Donation",
    mealPeriod: "Special Event",
    notes: "Cookies and cakes from department meeting",
  },
  {
    id: "8",
    date: "2024-04-18",
    source: "Cafeteria",
    foodType: "Grains",
    quantity: 6.3,
    disposalMethod: "Compost",
    mealPeriod: "Lunch",
    notes: "Rice and pasta leftovers",
  },
  {
    id: "9",
    date: "2024-04-19",
    source: "Residential",
    foodType: "Mixed Food",
    quantity: 7.1,
    disposalMethod: "Landfill",
    mealPeriod: "Dinner",
    notes: "Weekend leftovers from dorm",
  },
  {
    id: "10",
    date: "2024-04-19",
    source: "Cafeteria",
    foodType: "Vegetables",
    quantity: 4.8,
    disposalMethod: "Compost",
    mealPeriod: "Lunch",
    notes: "Cooked vegetables from hot bar",
  },
]

// Mock data for local farms
export interface Farm {
  id: string
  name: string
  distance: number // in miles
  products: string[]
  sustainable: boolean
  description: string
}

export const farms: Farm[] = [
  {
    id: "1",
    name: "Green Valley Organic Farm",
    distance: 12,
    products: ["Vegetables", "Fruits", "Herbs"],
    sustainable: true,
    description: "Family-owned organic farm using regenerative agriculture practices",
  },
  {
    id: "2",
    name: "Sunshine Dairy",
    distance: 15,
    products: ["Milk", "Cheese", "Yogurt"],
    sustainable: true,
    description: "Local dairy farm with grass-fed cows and sustainable practices",
  },
  {
    id: "3",
    name: "Riverbed Rice Farm",
    distance: 20,
    products: ["Rice", "Grains"],
    sustainable: true,
    description: "Sustainable rice farm using water-conserving techniques",
  },
  {
    id: "4",
    name: "Heritage Apple Orchard",
    distance: 18,
    products: ["Apples", "Pears", "Cider"],
    sustainable: true,
    description: "Historic orchard growing heirloom apple varieties with minimal pesticides",
  },
  {
    id: "5",
    name: "Community Vegetable Cooperative",
    distance: 5,
    products: ["Seasonal Vegetables", "Microgreens"],
    sustainable: true,
    description: "Urban farm cooperative run by community members using organic methods",
  },
]

// Mock data for user feedback
export interface Feedback {
  id: string
  dishId: string
  rating: number // 1-5 scale
  comment: string
  date: string
  username: string
}

export const feedbacks: Feedback[] = [
  {
    id: "1",
    dishId: "1",
    rating: 5,
    comment: "Love this healthy option! Perfect balance of flavors.",
    date: "2024-04-10",
    username: "healthyeater22",
  },
  {
    id: "2",
    dishId: "2",
    rating: 4,
    comment: "Great taste, but could use a bit more spice.",
    date: "2024-04-11",
    username: "spicylover",
  },
  {
    id: "3",
    dishId: "3",
    rating: 5,
    comment: "So filling and delicious! My go-to lunch option.",
    date: "2024-04-12",
    username: "veggielover",
  },
  {
    id: "4",
    dishId: "6",
    rating: 3,
    comment: "Tasty but I feel guilty about the carbon footprint.",
    date: "2024-04-13",
    username: "ecofriendly",
  },
  {
    id: "5",
    dishId: "7",
    rating: 5,
    comment: "Fresh and light! Perfect for a hot day.",
    date: "2024-04-14",
    username: "sushifan",
  },
]

// Mock data for dormitories/cafes for leaderboard
export interface Location {
  id: string
  name: string
  type: "Dormitory" | "Cafe" | "Dining Hall"
  wasteReduction: number // percentage
  sustainabilityScore: number // 1-100
  carbonSaved: number // in kg CO2e
}

export const locations: Location[] = [
  {
    id: "1",
    name: "Green Hall",
    type: "Dormitory",
    wasteReduction: 35,
    sustainabilityScore: 87,
    carbonSaved: 1250,
  },
  {
    id: "2",
    name: "Riverside Cafe",
    type: "Cafe",
    wasteReduction: 42,
    sustainabilityScore: 92,
    carbonSaved: 980,
  },
  {
    id: "3",
    name: "Central Dining Hall",
    type: "Dining Hall",
    wasteReduction: 28,
    sustainabilityScore: 75,
    carbonSaved: 2100,
  },
  {
    id: "4",
    name: "Science Building Cafe",
    type: "Cafe",
    wasteReduction: 31,
    sustainabilityScore: 79,
    carbonSaved: 850,
  },
  {
    id: "5",
    name: "East Campus Dorm",
    type: "Dormitory",
    wasteReduction: 25,
    sustainabilityScore: 68,
    carbonSaved: 920,
  },
]
